project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - weekly-notes/week-01-notes.qmd
    - weekly-notes/week-02-notes.qmd
    - weekly-notes/week-03-notes.qmd
    - weekly-notes/week-04-notes.qmd
    - weekly-notes/week-05-notes.qmd
    - weekly-notes/week-06-notes.qmd
    - weekly-notes/week-07-notes.qmd
    - weekly-notes/week-09-notes.qmd
    - labs/Zhang_Ye_Assignment2.qmd
    - labs/Zhang_Ye_Assignment1.qmd
    - labs/Zhang_Ye_Assignment4.qmd
    - labs/Zhang_Ye_Appendix.qmd
    - labs/presentation/presentation.qmd
    - labs/Tim_Ye_Assignment5.qmd

website:
  title: "Ye Zhang - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes 
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: Week 1
          - href: weekly-notes/week-02-notes.qmd
            text: Week 2
          - href: weekly-notes/week-03-notes.qmd
            text: Week 3
          - href: weekly-notes/week-04-notes.qmd
            text: Week 4
          - href: weekly-notes/week-05-notes.qmd
            text: Week 5
          - href: weekly-notes/week-06-notes.qmd
            text: Week 6
          - href: weekly-notes/week-07-notes.qmd
            text: Week 7
          - href: weekly-notes/week-09-notes.qmd
            text: Week 9
      - text: Assignment
        menu:
          - href: labs/Zhang_Ye_Assignment1.qmd
            text: Assignment 1
          - href: labs/Zhang_Ye_Assignment2.qmd
            text: Assignment 2
          - href: labs/Zhang_Ye_Appendix.qmd
            text: Midterm Appendix
          - href: labs/presentation/presentation.qmd
            text: Midterm Presentation
          - href: labs/Zhang_Ye_Assignment4.qmd
            text: Assignment 4
          - href: labs/Tim_Ye_Assignment5.qmd
            text: Assignment 5
            

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
